### ISSUE TITLE
Datapusher in Docker 

### ISSUE THREAD

**Issue by etj** [ckan/datapusher#228]
[Official ckan docker-compose file](https://github.com/ckan/ckan/blob/master/contrib/docker/docker-compose.yml) still references an image from `clementmouchet/datapusher`:

```
  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"
```
Anyway the clementmouchet master branch has last been updated on 23 Oct 2014, while the official repo reports "7 Oct 2020".

Is there a more recent official datapusher docker image than clementmouchet's one? Any work in progress on this?
